# Generated by Django 5.2.7 on 2026-02-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_healthdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdata',
            name='recommendation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='risk_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
