# Generated by Django 5.2.7 on 2026-02-19 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_healthdata_recommendation_healthdata_risk_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthdata',
            options={'ordering': ['-created_at'], 'verbose_name': "Sog‘liq ma'lumoti", 'verbose_name_plural': "Sog‘liq ma'lumotlari"},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': "Jamoa a'zosi", 'verbose_name_plural': "Jamoa a'zolari"},
        ),
        migrations.AddField(
            model_name='healthdata',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('past', 'Past xavf'), ('orta', 'O‘rta xavf'), ('yuqori', 'Yuqori xavf')], max_length=10, null=True, verbose_name='Xavf darajasi'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='chronic_disease',
            field=models.BooleanField(default=False, verbose_name='Surunkali kasalligi bor'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='close_contact',
            field=models.BooleanField(default=False, verbose_name='Kasallangan bilan yaqin aloqada bo‘lgan'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.teammember', verbose_name='Xodim'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='recommendation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tavsiya'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='risk_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Xavf balli'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='symptoms',
            field=models.BooleanField(default=False, verbose_name='Simptomlar mavjud'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='temperature',
            field=models.FloatField(verbose_name='Harorat (°C)'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='age',
            field=models.IntegerField(verbose_name='Yosh'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Ism familiya'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Lavozim'),
        ),
    ]
