# Generated by Django 5.2.7 on 2026-02-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_healthdata_options_alter_teammember_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Klinika nomi')),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
            ],
            options={
                'verbose_name': 'Klinika sozlamasi',
                'verbose_name_plural': 'Klinika sozlamalari',
            },
        ),
    ]
