# Generated by Django 5.2.7 on 2026-03-13 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_clinicsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Kasallik turi')),
                ('description', models.TextField(blank=True, verbose_name='Izoh')),
                ('isolation_required', models.BooleanField(default=False, verbose_name='Izolyatsiya kerak')),
            ],
            options={
                'verbose_name': 'Kasallik turi',
                'verbose_name_plural': 'Kasallik turlari',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Mutaxassislik nomi')),
                ('description', models.TextField(blank=True, verbose_name='Izoh')),
            ],
            options={
                'verbose_name': 'Shifokor mutaxassisligi',
                'verbose_name_plural': 'Shifokor mutaxassisliklari',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='healthdata',
            options={'ordering': ['-created_at'], 'verbose_name': "Sog'liq ma'lumoti", 'verbose_name_plural': "Sog'liq ma'lumotlari"},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['full_name'], 'verbose_name': 'Bemor', 'verbose_name_plural': 'Bemorlar'},
        ),
        migrations.AddField(
            model_name='healthdata',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_health_records', to=settings.AUTH_USER_MODEL, verbose_name="Ma'lumotni kiritgan"),
        ),
        migrations.AddField(
            model_name='teammember',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to=settings.AUTH_USER_MODEL, verbose_name="Mas'ul shifokor"),
        ),
        migrations.AddField(
            model_name='teammember',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Shifokor izohi'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='status',
            field=models.CharField(choices=[('kuzatuv', 'Kuzatuvda'), ('davolanish', 'Davolanishda'), ('barqaror', 'Barqaror')], default='kuzatuv', max_length=20, verbose_name='Holati'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='close_contact',
            field=models.BooleanField(default=False, verbose_name="Kasallangan bilan yaqin aloqada bo'lgan"),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.teammember', verbose_name='Bemor'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('past', 'Past xavf'), ('orta', "O'rta xavf"), ('yuqori', 'Yuqori xavf')], max_length=10, null=True, verbose_name='Xavf darajasi'),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='temperature',
            field=models.FloatField(verbose_name='Harorat (C)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='disease_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='team.diseasetype', verbose_name='Kasallik turi'),
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='Xona')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='team.doctorspecialty', verbose_name='Mutaxassisligi')),
            ],
            options={
                'verbose_name': 'Shifokor profili',
                'verbose_name_plural': 'Shifokor profillari',
                'ordering': ['user__username'],
            },
        ),
    ]
