# Generated by Django 5.2.7 on 2026-03-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_seed_reference_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsolationCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Markaz nomi')),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('capacity', models.PositiveIntegerField(default=0, help_text='Qabul qila oladigan bemorlar soni', verbose_name="Sig'im (kishi)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
            ],
            options={
                'verbose_name': 'Izolyatsiya markazi',
                'verbose_name_plural': 'Izolyatsiya markazlari',
                'ordering': ['name'],
            },
        ),
    ]
