# Generated by Django 5.2.7 on 2026-03-18 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_region_and_member_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='isolationcenter',
            name='infrastructure_score',
            field=models.PositiveSmallIntegerField(default=5, help_text="0-10 oralig'ida baholang", verbose_name='Infratuzilma balli'),
        ),
        migrations.AddField(
            model_name='isolationcenter',
            name='occupancy_rate',
            field=models.PositiveSmallIntegerField(default=0, help_text="0-100 oralig'ida joriy bandlik foizi", verbose_name='Bandlik foizi'),
        ),
        migrations.AddField(
            model_name='isolationcenter',
            name='readiness_score',
            field=models.PositiveSmallIntegerField(default=5, help_text="0-10 oralig'ida baholang", verbose_name='Tezkor tayyorgarlik balli'),
        ),
        migrations.AddField(
            model_name='isolationcenter',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isolation_centers', to='team.region', verbose_name='Hudud'),
        ),
        migrations.AddField(
            model_name='isolationcenter',
            name='travel_time_minutes',
            field=models.PositiveIntegerField(default=30, help_text="Markazga o'rtacha yetib borish vaqti", verbose_name='Yetib borish vaqti (daq)'),
        ),
    ]
