"""
Django settings for isolation_system project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

BASE_DIR = Path(__file__).resolve().parent.parent

# =========================
# SECURITY
# =========================

SECRET_KEY = os.environ.get("SECRET_KEY", "dev-secret-key")

DEBUG = os.environ.get("DEBUG", "False") == "True"

ALLOWED_HOSTS = os.environ.get(
    "ALLOWED_HOSTS",
    "localhost,127.0.0.1"
).split(",")

CSRF_TRUSTED_ORIGINS = [
    "https://isolation-system.onrender.com",
    "https://*.onrender.com",
]

# =========================
# APPLICATIONS
# =========================

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'team',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # production static
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'isolation_system.urls'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'

# =========================
# TEMPLATES
# =========================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'isolation_system.wsgi.application'

# =========================
# DATABASE
# =========================

if os.environ.get("DATABASE_URL"):
    DATABASES = {
        'default': dj_database_url.parse(
            os.environ.get("DATABASE_URL"),
            conn_max_age=600
        )
    }
else:
    # Local uchun SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# =========================
# PASSWORD VALIDATION
# =========================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# =========================
# INTERNATIONAL
# =========================

LANGUAGE_CODE = 'uz'
TIME_ZONE = 'Asia/Tashkent'
USE_I18N = True
USE_TZ = True

# =========================
# STATIC FILES
# =========================

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Faqat mavjud papkalarni qo'shish
import os as _os
_static_dir = BASE_DIR / "static"
STATICFILES_DIRS = [_static_dir] if _static_dir.exists() else []

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =========================
# UNFOLD
# =========================

UNFOLD = {
    "SITE_TITLE": "Klinika Admin",
    "SITE_HEADER": "Sog'liq Monitoring",
    "SITE_SUBHEADER": "Klinika boshqaruv tizimi",
    "SITE_SYMBOL": "health_and_safety",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SHOW_BACK_BUTTON": True,
    "SHOW_LANGUAGES": False,

    "COLORS": {
        "font": {
            "subtle-light": "107 114 128",
            "subtle-dark": "156 163 175",
            "default-light": "17 24 39",
            "default-dark": "229 231 235",
            "important-light": "17 24 39",
            "important-dark": "243 244 246",
        },
        "primary": {
            "50":  "240 253 244",
            "100": "220 252 231",
            "200": "187 247 208",
            "300": "134 239 172",
            "400": "74 222 128",
            "500": "34 197 94",
            "600": "22 163 74",
            "700": "21 128 61",
            "800": "20 83 45",
            "900": "14 60 33",
            "950": "5 46 22",
        },
    },

    "EXTENSIONS": {
        "modeltranslation": {
            "flags": {},
        },
    },

    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Asosiy",
                "separator": False,
                "collapsible": False,
                "items": [
                    {
                        "title": "Boshqaruv paneli",
                        "icon": "dashboard",
                        "link": "/admin/",
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": "Saytga o'tish",
                        "icon": "open_in_new",
                        "link": "/dashboard/",
                    },
                ],
            },
            {
                "title": "Jamoa boshqaruvi",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Jamoa a'zolari",
                        "icon": "group",
                        "link": "/admin/team/teammember/",
                        "badge": "team.views.get_member_count",
                    },
                    {
                        "title": "Sog'liq ma'lumotlari",
                        "icon": "monitor_heart",
                        "link": "/admin/team/healthdata/",
                    },
                    {
                        "title": "Klinika sozlamalari",
                        "icon": "settings_suggest",
                        "link": "/admin/team/clinicsettings/",
                    },
                ],
            },
            {
                "title": "Tizim boshqaruvi",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Foydalanuvchilar",
                        "icon": "manage_accounts",
                        "link": "/admin/auth/user/",
                    },
                    {
                        "title": "Guruhlar",
                        "icon": "groups",
                        "link": "/admin/auth/group/",
                    },
                ],
            },
        ],
    },

    "TABS": [
        {
            "models": ["team.teammember"],
            "items": [
                {"title": "Jamoa a'zolari", "link": "/admin/team/teammember/"},
                {"title": "Sog'liq ma'lumotlari", "link": "/admin/team/healthdata/"},
            ],
        },
    ],
}

# Session brauzer yopilganda tugaydi
SESSION_EXPIRE_AT_BROWSER_CLOSE = True